Configparse
conchyliculture/NvapiFans pull request #1
Opened 2020-04-07 20:40 UTC by conchyliculture

If config.json (template provided) is dropped in C:\ProgramData\NvapiFansSvc\, uses that as configuration for the service.

2020-04-09 08:02 UTC, x0rbl requested changes

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>  }
This review tool won't let me comment on unchanged lines, so I'm going to stuff a extra comments for this file here instead, prefixed by line number:

157: `message` should be const reference
170: `message` should be const reference (optionally, I would also call this `LogInfo` and use `EVENTLOG_INFORMATION_TYPE`, which is effectively the same thing)

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +void GetLastErrorAsString(std::wstring &message)
I think the code was a little more compact with it returning a `wstring` vs accepting/modifying one. Additionally, the former method was sure to return the empty string instead of leaving whatever was in `message` beforehand without any indication that `GetLastError` returned ERROR_SUCCESS.

But if you want, there _is_ an associated string for 0 (see [here](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)), so you could still pass the 0 along to `FormatMessage` anyway.

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +bool parseConfig(HANDLE event_log, std::wstring config_path, service_config_t& service_config) {
`config_path` should be const reference

Also `parseConfig` can still modify `service_config` and return `false`. If that is expected behavior, I'd leave a comment explaining that.

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if (SHGetKnownFolderPath(FOLDERID_ProgramData, NULL, 0, &szPath) >= 0) {
For success, you should check if `SHGetKnownFolderPath(...) == S_OK` (see [here](https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath))

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    //   LogError(event_log, std::wstring_convert(errmsg));
I don't think you need this :)

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    //Free the buffer.
Comment probably unnecessary

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        GetLastErrorAsString(error_message);
Does SHGetKnownFolderPath actually set LastErrorValue? It doesn't say that it does on MSDN

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int start_fan_temp_C = NVAPIFANSSVC_START_FAN_TEMP_DEFAULT; // We're confortable with letting the GPU go this hot before turning the fan on
comfortable*

2020-04-09 08:02 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int start_fan_temp_C = NVAPIFANSSVC_START_FAN_TEMP_DEFAULT; // We're confortable with letting the GPU go this hot before turning the fan on
For some clarification regarding these variables:

- Is `target_temp_max_C` the temperature that we always prefer the CPU to be at?  That is to say, if we're above this temperature, turn the fans up higher (if possible), and if we're below this temperature, turn the fans lower (or off)?
- Does `min_fanspeed_percent` mean that the fan will _always_ be running at this speed or faster, regardless of temperature?  Or only when the temperature is greater than or equal to `start_fan_temp_C`?  It seems like these two lines contradict each other.

(I think it's okay to be more verbose in the documentation here)

2020-04-09 08:17 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	for (NV_PHYSICAL_GPU_HANDLE &gpu : list_gpu) {
done, except for like 95 (which changes state of object api)

2020-04-09 08:20 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>  }
done

2020-04-09 09:13 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +void GetLastErrorAsString(std::wstring &message)
done

2020-04-09 09:14 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if (SHGetKnownFolderPath(FOLDERID_ProgramData, NULL, 0, &szPath) >= 0) {
done

2020-04-09 09:17 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +bool parseConfig(HANDLE event_log, std::wstring config_path, service_config_t& service_config) {
fixed

2020-04-09 09:18 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          }
fixed

2020-04-09 09:18 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        GetLastErrorAsString(error_message);
haha no idea.
Removing

2020-04-09 09:24 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int start_fan_temp_C = NVAPIFANSSVC_START_FAN_TEMP_DEFAULT; // We're confortable with letting the GPU go this hot before turning the fan on
oh right, comments suck there
changed.

2020-04-09 09:30 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          }
comment was 

This review tool won't let me comment on unchanged lines, so I'm going to stuff a extra comments for this file here instead, prefixed by line number:

8: api should be const reference
52: api should be const reference
78: list_gpu should be const reference
95: api should be const reference

In each of these functions, the object is being passed by copy, which means that you need to construct a duplicate object each time one of these functions is called. In the case of api, that also means calling the NvApiClient constructor that makes several calls into nvapi[64].dll all over again, etc.

2020-04-09 18:49 UTC, x0rbl requested changes

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.h
>      void getNvAPIError(NvAPI_Status status, std::string message);
`void getNvAPIError(NvAPI_Status status, std::string& message);`

Note that the implementation in NvapiFansLib.cpp sets `message`, which won't do anything for the caller function, since `message` is a copy rather than a reference.

Also this method can be static, since it doesn't use the underlying `NvApiClient` object.  Or, if you don't plan on using it outside of NvapiFansLib.cpp, then it doesn't even need to be a part of the class.

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.h
> +    int percentToHex(byte hex) const;
These should be static, rather than const.  Or if you don't plan on using these functions outside of NvapiFansLib.cpp, then they don't need to be a part of the class.

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +void LogError(const HANDLE &event_log, const std::wstring &message) {
`HANDLE` is just a primitive type (`void*`) so it's fine to pass by copy.  Generally you pass pointers/references to instances of structs/classes.

(Also applies to `LogInfo` below)

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        std::wcout << GetLastErrorAsString() << std::endl;
Stuff like this is tricky.  Many Windows APIs (but certainly not all) will set the `LastErrorValue` in the [thread environment block](https://www.geoffchappell.com/studies/windows/win32/ntdll/structs/teb/index.htm) after an operation.  This is what `GetLastError` gives you.  So generally speaking, you should call `GetLastError` immediately after an API that sets it, or else some other operation (on the same thread) might set `LastErrorValue` to something else.

I don't know how `std::cout` is implemented in MSVC, but if that line internally calls some API that sets `LastErrorValue` then you're going to get different results in lines 361 and 363.

So your options are:

1. You could store the result of `GetLastError` and then store the result of `GetLastErrorAsString` *in that order* before writing any output (the order matters because `FormatMessage` sets `LastErrorValue`), or
2. Repurpose `GetLastErrorAsString` to be more like `std::wstring ErrorToString(DWORD ErrorValue)` (which would involve changing invocations to `ErrorToString(GetLastError())` or `ErrorToString(err)`)

I recommend the latter.

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	for (NV_PHYSICAL_GPU_HANDLE &gpu : list_gpu) {
I'm not certain that the reference is useful here

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            parseConfig(event_log, config_path_w, service_config);
Now that `parseConfig` won't modify `service_config` on failure, do you want to propagate the failure here as well?  Would a failure to load the configuration from disk would mean `loadConfig` failed?  If you're worried about not getting the "Applying config" message a few lines below, you could move that out of this function and into `serviceWorkerThread` to say what the current configuration is, regardless of whether a configuration load was successful or not.

(Remember, if you exit the function prematurely, you'll want to make sure you're still calling `CoTaskMemFree(szpath)`)

2020-04-09 18:49 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    LogInfo(event_log, L"Config loaded");
This line displays regardless of whether or not a configuration file was loaded.  Is that what you want?

(Also as a future note, once this code is finished, you might want to come back and remove some of the redundant "info" event log messages so there is not too much spam)

2020-04-09 19:05 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.h
>      void getNvAPIError(NvAPI_Status status, std::string message);
done
getNvAPIError uses NvAPI_GetErrorMessage, which is resolved in the class constructor, so it stays in the class.

2020-04-09 19:05 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.h
> +    int percentToHex(byte hex) const;
done

2020-04-09 19:37 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        std::wcout << GetLastErrorAsString() << std::endl;
done with 2.

2020-04-09 19:38 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	for (NV_PHYSICAL_GPU_HANDLE &gpu : list_gpu) {
fixed

2020-04-09 19:40 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    LogInfo(event_log, L"Config loaded");
yeah this is definitely very verbose right now, helps with not having any idea what I'm doing =)

Maybe this can still go in a logfile

2020-04-09 19:40 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +void LogError(const HANDLE &event_log, const std::wstring &message) {
done

2020-04-09 19:43 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            parseConfig(event_log, config_path_w, service_config);
moved logging the config in the main loop of the worker thread

2020-04-10 05:25 UTC, x0rbl requested changes

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.cpp
> +bool NvApiClient::I2CReadByteEx(const NV_PHYSICAL_GPU_HANDLE &gpu, byte deviceAddress, byte registerAddress, byte *data) const {
This is functionally correct, but since `NV_PHYSICAL_GPU_HANDLE` is just an opaque pointer (defined in your headers as `int*`), it's more standard to pass it by value than by a const reference.  (Same reasoning as with `HANDLE` in the last review, which is just `void*`)

Also applies to: `I2CWriteByteEx`, `getGPUFullName`, `getExternalFanSpeedPercent`, `getExternalFanSpeedRPM`, `setExternalFanSpeedPercent`, `getTemps`, `getGPUTemperature`

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.h
>      void getNvAPIError(NvAPI_Status status, std::string message);
You can get rid of this extra function declaration (I don't think it is defined anywhere), and the method by the same name is correct

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
>  VOID WINAPI ServiceMain(DWORD argc, LPTSTR* argv);
Actually, if you're removing the declarations for `LogError`, `LogSuccess`, etc. then I think you can remove the other function declarations in this file as well (`ServiceMain` through `ServiceCtrlHandler`).  I don't think that they're needed for anything either.

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        for (NV_PHYSICAL_GPU_HANDLE &gpu : list_gpu) {
Same comment as with the similar section in NvapiFansCli.cpp: I'm not certain that the reference is useful here

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          return std::wstring(); //No error message has been recorded
I think a merge might have gotten messed up or something; you can remove these three lines

2020-04-10 05:25 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        NULL, errorMessageID, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPTSTR)&lpMsgBuf, 0, NULL);
`error_value`, not `errorMessageID`

2020-04-10 08:00 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.cpp
> +bool NvApiClient::I2CReadByteEx(const NV_PHYSICAL_GPU_HANDLE &gpu, byte deviceAddress, byte registerAddress, byte *data) const {
done

2020-04-10 08:08 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          return std::wstring(); //No error message has been recorded
yeah merges are the worst

2020-04-10 08:18 UTC, x0rbl approved these changes

2020-04-10 08:19 UTC, merged