Use logfile instead of WinEvt
conchyliculture/NvapiFans pull request #15
Opened 2020-04-12 12:41 UTC by conchyliculture

2020-04-14 08:17 UTC, x0rbl requested changes

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +			bool level = QUIET;
This should be a `LogLevel`, not a `bool`

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +			};
You want to set `level` too, right?  You can use [member initializer lists](https://www.learncpp.com/cpp-tutorial/8-5a-constructor-member-initializer-lists/) if you want:

`Logger(std::string filename_, int level_) : filename{filename_}, level{level_}{}`

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +					return
You're missing a semi-colon.   This function is the equivalent of:

```
if (level > INFO) {
  return tryOpen();
}
stream << [...];
```

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +					return
Same as above; there is a missing semicolon here too

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        OutputDebugString(NVAPIFANSSVC_SVC_NAME _T(" ServiceMain: Couldn't CreateThread"));
I think you also want the `_T()` wrapper here to match the one you're joining with

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            }
You can remove this (this is a duplicate of the code above, and it doesn't make sense to be in this block

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            }
Not particularly important, you could handle the case where `log_level` is defined but it isn't any of `"quiet"`, `"info"`, or `"debug"` by failing here if you want

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            EventLogError(event_log, L"Can't find config file: " + config_path.wstring());
You still return true if you hit this case, which seems a little weird.  Here's what I suggest:

1. Only have one `CoTaskMemFree(szPath)` line, and put it directly after you copy its contents into `appdata`
2. Move the line where you set `service_config.log_filepath` above the check for the config path, right after you've determined that the config directory exists
3. Return `false` after logging the error on the highlighted line
4. Drop the else (save an indentation)
5. Save another bit of indentation by handling the `SHGetKnownFolderPath` error case up top (I think that is more readable)

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +				tryOpen();
See my comment below, but I think you should actually have four log levels: Debug, Info, **Error**, and Quiet.  Error will still display errors (we'll need a check for `(level > ERROR)` here).  Quiet won't display anything at all.  We need to ensure we have a mode where the logger just won't try to open a file no matter what (in case the log directory can't exist)

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +	enum LogLevel { DEBUG, INFO, QUIET };
I think we need four log levels; see my comment below for a justficiation

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    SillyLogger::Logger logger(service_config.log_filepath.string(), service_config.log_level);
Note that `service_config.log_filepath` can be the empty string.  This can happen as the result of a few different error cases of `loadConfig`

If you try to construct a `Logger` with a `filepath` as `""` then you're just going to raise an exception in `tryOpen`.  However, we can prevent that if we make it so that the "quiet" logging mode just never tries to create the output stream.  Right now it opens it for errors no matter what.  This is why I suggest that you create a fourth logging level between `INFO` and `QUIET`, just for errors.

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        return ERROR_BAD_COMMAND; // Maybe find a better error but eh
You can do whatever you want here, but I'm commenting just to check if the difference in error code between this and the above cases was intentional

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        EventLogError(event_log, utf8_decode(e.code().message()));
We don't want to return `ERROR_SUCCESS` if we reach this block.  [Pick your favorite](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) :)

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    logger.Info("Service Stopped");
If logging threw an exception a few lines up you don't want to be attempting to log again.  Move this line just outside the `while (WaitForSingleObject(...) != WAIT_OBJECT_0) {...}` block

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +                    EventLogError(event_log, L"Error calling setExternalFanSpeedPercent");
Is using the event log vs `Logger` intentional here?

2020-04-14 08:17 UTC, x0rbl commented on win/config.json
> +    "log_level":  "quiet",
Let's make the default "error" (see my suggestion above regarding that)

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>      // Wait until our worker thread exits signaling that the service needs to stop
After `WaitForSingleObject(hThread, INFINITE)` in the line below, you should call [GetExitCodeThread](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodethread) and set the exit code of the service.  Now the return value that you give from `ServiceWorkerThread` will actually be accessible.

```
DWORD exit_code = -1;
GetExitCodeThread(hThread, &exit_code);
...
g_ServiceStatus.dwWin32ExitCode = exit_code;
```

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    try {
I think this `try` block is located in a weird spot.  We gracefully handle errors in the logger here but not in the `logger.{Debug|Info|Error}` calls just above, which is where an exception would occur (if anywhere) for INFO/DEBUG modes.

I'm inclined to think that you don't need to throw exceptions in this code at all though.

One option is to silently let the logger fail when there is a problem:  Force the logger into "quiet" mode, close the stream, and unset `opened`.

Another option (if you absolutely don't want the service to run without logging) is to return `bool` from the logging functions to indicate whether they worked or not.  And then immediately after you open the logger, force it to open/write to the log file with `Flush()`.  You can check the return value there.  If it worked, you can continue on as normal.

2020-04-14 08:17 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    catch (std::fstream::failure e) {
I think this _might_ work either way, but you've written the exception that you throw as `std::iostream::failure` and you written the exception that you catch as `std::fstream::failure`.

(I don't see any other places where you would be throwing exceptions.  The C++ streams won't do it themselves you tell them to via [`ios::exceptions`](http://www.cplusplus.com/reference/ios/ios/exceptions/), which I do not recommend)

2020-04-14 08:32 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
> +			bool level = QUIET;
done

2020-04-14 08:34 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
> +			};
done

2020-04-14 08:35 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
> +					return
done

2020-04-14 08:36 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        OutputDebugString(NVAPIFANSSVC_SVC_NAME _T(" ServiceMain: Couldn't CreateThread"));
done

2020-04-14 08:36 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            }
fixed

2020-04-14 08:37 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            }
I'd rather just ignore and keep default

2020-04-14 08:45 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            EventLogError(event_log, L"Can't find config file: " + config_path.wstring());
done

2020-04-14 08:50 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    SillyLogger::Logger logger(service_config.log_filepath.string(), service_config.log_level);
done

2020-04-14 08:51 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        return ERROR_BAD_COMMAND; // Maybe find a better error but eh
I don't remember. I think it was =)

2020-04-14 08:54 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        EventLogError(event_log, utf8_decode(e.code().message()));
done

2020-04-14 08:55 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    logger.Info("Service Stopped");
done

2020-04-14 08:55 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +                    EventLogError(event_log, L"Error calling setExternalFanSpeedPercent");
nope, fixing

2020-04-14 08:56 UTC, conchyliculture commented on win/config.json
> +    "log_level":  "quiet",
done

2020-04-14 08:57 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>      // Wait until our worker thread exits signaling that the service needs to stop
done

2020-04-14 08:58 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    catch (std::fstream::failure e) {
done

2020-04-14 09:01 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    try {
removed exception throwing

2020-04-15 07:24 UTC, x0rbl requested changes

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
>  			std::string timestamp() const {
This method doesn't access the state, so I think you should pull it out of the class or make the method static

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +                    return;
Fix whitespace formatting

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
>  			void Error(std::string message) {
Make the string parameter a const reference in these functions:

1. The `Logger` constructor
2. `Error`
3. `Info`
4. `Debug`

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
>  				stream << timestamp() + " Debug: " + message << std::endl;
(Optional) `" DEBUG: "` (to match the other capitalization)

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +                    }
Fix indentation

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    const std::wstring config_path_w = config_path.wstring();
Put this above the config file check (but after the config _directory_ check) so that you'll still get logging even if the config file doesn't exist

(Even though it seems that the default value in `service_config_t` is `LOGLEVEL_QUIET` anyway; see the other comment about this)

2020-04-15 07:24 UTC, x0rbl commented on win/README.md
> +                             // either "quiet", "error",  "info", or "debug". Default is "error". "quiet" will not log anything. "error" will just log errors. "info" will log fan speed changes. "debu
`Default is "error".`

That doesn't seem to be true, given that `service_config_t` has `log_level` default to `LOGLEVEL_QUIET`.  I agree that "error" seems like a good default value though.

(Nitpick: You also have an extra space between "error" and "info")

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
> +			LogLevel level = LOGLEVEL_ERROR;
This line might be a bit misleading:  The initialization that you set here isn't the actual default value -- it just gets overwritten because the only constructor for `Logger` sets `level`.  The actual default value lies is `log_level` in `service_config_t`.  It might be less confusing to just not set an initial value here.

2020-04-15 07:24 UTC, x0rbl commented on win/NvapiFansSvc/Logger.hpp
>  					stream.open(filename, std::ofstream::out | std::ofstream::app);
If `loadConfig` fails before you set `log_filepath`, you'll end up passing the empty string as the log path to `Logger`.  This will end up failing gracefully (on this line) when you try to open the file path, which is exactly what we want.

But I think it should be document behavior for `Logger` that passing the empty string for the log path means that no logging will be performed.  So:

1. I'd add a comment to clarify that
2. I'd also have a check here in `tryOpen` such that if the path is `""` that it will just set `level` to `LOGLEVEL_QUIET` right off the bat

2020-04-15 07:32 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
>  			std::string timestamp() const {
but then it'd require 4 params

2020-04-15 07:35 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
>  			std::string timestamp() const {
done

2020-04-15 07:36 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
>  			void Error(std::string message) {
done

2020-04-15 07:37 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    const std::wstring config_path_w = config_path.wstring();
done

2020-04-15 07:39 UTC, conchyliculture commented on win/README.md
> +                             // either "quiet", "error",  "info", or "debug". Default is "error". "quiet" will not log anything. "error" will just log errors. "info" will log fan speed changes. "debu
done

2020-04-15 07:40 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
> +			LogLevel level = LOGLEVEL_ERROR;
done

2020-04-15 07:42 UTC, conchyliculture commented on win/NvapiFansSvc/Logger.hpp
>  					stream.open(filename, std::ofstream::out | std::ofstream::app);
done

2020-04-15 08:10 UTC, x0rbl approved these changes

2020-04-15 08:11 UTC, merged