Add Linux driver & doc (WiP)
conchyliculture/NvapiFans pull request #16
Opened 2020-04-14 10:27 UTC by conchyliculture

2020-04-17 06:42 UTC, x0rbl requested changes

2020-04-17 06:42 UTC, x0rbl commented on linux/asus_fc2_module/asus_fc2.c
> +  0x68 // Is apparently exactly the same as 0x2a
Put this all on one line

2020-04-17 06:42 UTC, x0rbl commented on linux/asus_fc2_module/asus_fc2.c
> +  dev = &client->dev;
Duplicate of line 115; you can remove this

2020-04-17 06:42 UTC, x0rbl commented on linux/asus_fc2_module/asus_fc2.c
> +  return 0;
The double switch is a little confusing.  Feel free to disregard if this is the preferred style (I notice switches are used everywhere else).  But probably the most readable way to write it is:

```
if (type == hwmon_pwm && attr == hwmon_pwm_input) {
  return 0644;
}
return 0;
```

2020-04-17 06:57 UTC, conchyliculture commented on linux/asus_fc2_module/asus_fc2.c
> +  0x68 // Is apparently exactly the same as 0x2a
who are you to defy clang-format? :3

2020-04-17 07:00 UTC, conchyliculture commented on linux/asus_fc2_module/asus_fc2.c
> +  return 0;
oh it's just because here I ended up with very few options (only type=pwm & attr = pwm_input)

2020-04-18 02:13 UTC, x0rbl approved these changes

2020-04-19 16:29 UTC, merged