Actually implement Temperature handling logic
conchyliculture/NvapiFans pull request #5
Opened 2020-04-08 21:04 UTC by conchyliculture

2020-04-10 19:11 UTC, djdeath commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        errmsg += "Error in config file: bad value for interval_s: " + std::to_string(draft_config.gpu_config.interval_s);
LOL I can't believe you're not using the `<<` operator. Noob.

2020-04-10 19:14 UTC, djdeath commented on win/NvapiFansLib/NvapiFansLib.cpp
>  	int hex_val = (int)hex;
You could drop that local variable.

2020-04-10 19:14 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        errmsg += "Error in config file: bad value for interval_s: " + std::to_string(draft_config.gpu_config.interval_s);
isn't that for streams only?

2020-04-10 19:26 UTC, djdeath commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        errmsg += "Error in config file: bad value for interval_s: " + std::to_string(draft_config.gpu_config.interval_s);
I meant `std::stringstream` so that you can do :

```
std::stringstream err;

err << "My message";
```

But it was kind of a c++ joke ;)

2020-04-10 21:08 UTC, x0rbl requested changes

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	std::cout << "  * GPU Utilization: " << utilization << "%" << std::endl;
Maybe do a special case for when `utilization` is -1?

(Same for the other variables)

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        errmsg += "Error in config file: bad value for interval_s: " + std::to_string(draft_config.gpu_config.interval_s);
You're going to want some kind of delimiter between these pieces of `errmsg` in case there are more than one.  Put a new line at the end of each.

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.h
> +    void getNvAPIError(NvAPI_Status status, std::string& message) const;
If the return value is void, then we might as well make this return `std::string` instead of setting it by reference

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansCli/NvapiFansCli.cpp
> +		#pragma clang diagnostic ignored "-Wswitch"
Does putting `default:` at the bottom of the switch statement suppress this warning?

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          int index = 0;
You can remove the `index` variable as it's not being used anymore.  (Also it's not being tracked consistently anyway; hitting a `continue` statement will skip the increment at the bottom of the loop)

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_fan_speed = 200; // Speed to set if temp is over max_temp_c. 255 is "max speed"
I'd also specify that the range is 0-255 for these values (like above)

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if ((draft_config.gpu_config.interval_s < 0) || (draft_config.gpu_config.interval_s > 100) ) {
Do you mean `draft_config.gpu_config.interval_s <= 0`?  I don't think you would want `interval_s` to be zero, because then your only throttling would be a `Sleep(0)` down below, which could spin the CPU.

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int interval_s = 2; // Which interval in seconds between checks
Specify the allowable range (1-100) so that a user who sets this to something larger doesn't get confused by the error.  Also see the comment above about 0 not being included in the range.

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    else if (current_temp >= service_config.gpu_config.max_temp_c) {
Since you're returning in each condition, you don't need the `else` here or below.  That will save you some indentation below.

2020-04-10 21:08 UTC, x0rbl commented on README.md
> +        "average": 1, // How many last temp readings are used to average the temperature
My comments regarding the documentation below apply here too

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            pushTemp(service_config, currentTemp);
I might be misunderstanding the purpose of `average` so please correct me if I'm wrong.  (And if I am wrong, also clarify in the documentation what `average` is for)

We aren't using the history of the temperatures for anything, or ever calculating an average.  My assumption is that `average` would determine how much we smooth the recent temperature readings as part of the calculation of the correct fan speed.  If so, we should push the current temperature into the history _first_, and the function that does this (`pushTemp`) should calculate and return the average.  We would then pass that average value into `getNewSpeed`.

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_temp_c = 80;// Above this, fan switches to its "maximum speed"
You might as well specify the valid range of values here too (0-100), or at least say that 100°C is the max.

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int min_fan_stop_speed = 25; // This is the minimum speed at which the fan begins spinning, between 0 & 255
These two lines have the exact same documentation.

Maybe it would help to briefly explain why this is in the configuration, because it wouldn't have been obvious to me without prior knowledge that the fans don't spin at certain lower speeds.  I'm also getting confused about what "start" and "stop" mean here

Furthermore, we don't use `min_fan_start_speed`; what does it mean?  We only use `min_fan_stop_speed`.  Do we need it?

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        LogError(event_log, utf8_decode(errmsg + "custom config ignored\n"));
You could remove `"Error in config file: "` from each of the above strings, and then you could log something like this here:

`"Errors in config file:\n" + errmsg + "Custom config ignored"`

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int average = 1; // How many last temp readings are used to average the temperature
Specify a valid range here too (1-100).  Also see my other comment about clarifying the purpose of `average` in the documentation

2020-04-10 21:08 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if (draft_config.gpu_config.min_fan_speed > draft_config.gpu_config.max_fan_speed) {
Should we also make sure that `min_fan_stop_speed` is in the range of `min_fan_speed` to `max_fan_speed` (inclusive)?

2020-04-10 21:26 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	std::cout << "  * GPU Utilization: " << utilization << "%" << std::endl;
Ternary to the rescue :3

2020-04-10 21:27 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        errmsg += "Error in config file: bad value for interval_s: " + std::to_string(draft_config.gpu_config.interval_s);
done

2020-04-10 21:33 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.h
> +    void getNvAPIError(NvAPI_Status status, std::string& message) const;
done

2020-04-10 21:34 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +		#pragma clang diagnostic ignored "-Wswitch"
maaaaybe

2020-04-10 21:35 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
>          int index = 0;
done

2020-04-10 21:35 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_fan_speed = 200; // Speed to set if temp is over max_temp_c. 255 is "max speed"
done

2020-04-10 21:36 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if ((draft_config.gpu_config.interval_s < 0) || (draft_config.gpu_config.interval_s > 100) ) {
oh right fixed

2020-04-10 21:37 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int interval_s = 2; // Which interval in seconds between checks
done

2020-04-10 21:38 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    else if (current_temp >= service_config.gpu_config.max_temp_c) {
done

2020-04-10 21:39 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            pushTemp(service_config, currentTemp);
yes, the averaging part is not implemented, it's just made of lies for now =)

2020-04-10 21:41 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            pushTemp(service_config, currentTemp);
https://github.com/conchyliculture/NvapiFans/issues/13
Here's an issue, which is basically like code

2020-04-10 21:43 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_temp_c = 80;// Above this, fan switches to its "maximum speed"
done

2020-04-10 21:57 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int min_fan_stop_speed = 25; // This is the minimum speed at which the fan begins spinning, between 0 & 255
Updated the comment.
I added a line to set speed to min_fan_start_speed, if we're currently not running, and we would have set a PWM value lower than that otherwise

2020-04-10 21:58 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        LogError(event_log, utf8_decode(errmsg + "custom config ignored\n"));
done

2020-04-10 21:59 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int average = 1; // How many last temp readings are used to average the temperature
done

2020-04-10 22:01 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if (draft_config.gpu_config.min_fan_speed > draft_config.gpu_config.max_fan_speed) {
done

2020-04-10 22:05 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.cpp
>  	int hex_val = (int)hex;
done

2020-04-11 18:35 UTC, djdeath commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	bool res = true;
Could move that bool where it's needed (line 119)

2020-04-11 19:59 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	bool res = true;
done

2020-04-11 21:00 UTC, x0rbl requested changes

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	utilization = api.getGPUUsage(gpu);
Here (and for all of the variables above), you can declare and assign them in the same line, like

`int speedCmd = api.getExternalFanSpeedPercent(gpu);`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        service_config_t config_service{};
You already have `service_config` defined above (which you set via `loadConfig`).  Remove `config_service` and continue to use `service_config`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_temp_c = 80;    // Above this, fan switches to its "maximum speed", max 100
Recommending:
`At this temperature or lower, the service will run the fan at min_fan_speed. Celsius, range 0-100`
`At this temperature or higher, the service will run the fan at max_fan_speed. Celsius, range 0-100`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if ((draft_config.gpu_config.interval_s <= 1) || (draft_config.gpu_config.interval_s > 100) ) {
You want `(draft_config.gpu_config.interval_s <= 0)` or `(draft_config.gpu_config.interval_s < 1)`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int interval_s = 2;     // Which interval in seconds between checks, between 1 & 100
Recommending:
`The frequency at which the service checks the GPU temperature and adjusts the fan speed. Seconds, range 1-100`

(But since this is seconds, maybe the max would be better with something like 15, 30, 60, or 120?)

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_fan_speed = 200;         // Speed to set if temp is over max_temp_c. 255 is "max speed", between 0 & 255
Recommending:
`The speed at which the service will run the fan when the GPU temperature is less than or equal to min_temp_c. Range 0-255. A value of 0 indicates that the fan will not spin`
`The speed at which the service will run the fan when the GPU temperature is greater than or equal to max_temp_c. Range 0-255.`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int min_fan_stop_speed = 25;     // This is the minimum speed at which the fan keeps spinning once started, between 0 & 255 aka minso
Recommending:

`min_fan_start_speed`:
`When the fan is stopped, this is the minimum speed at which the fan will start spinning. Range 0-255`

`min_fan_stop_speed` -- These have slightly different meanings, but use one of these (I prefer the former, given the name):
`When the fan is spinning, this is the maximum speed at which the fan will stop spinning. Range 0-255`
`When the fan is already spinning, this is the lowest speed at which the fan will continue spinning. Range 0-255`

And **then** I would explain to the user how they can determine these values.  Two things come to mind, and if both are applicable, I'd mention both.

1. If you can look this up somewhere, I'd add a sentence explaining where they could look.  (For example, does the fan manufacturer typically document these values in a manual?)
2. They can use the cli tool to experimentally determine the values, right?  I would add a little text file briefly explaining how a user can get the right values.  If you don't want to do that right now, just add a TODO.

And one more thing:  Very optional, but I think I would call these `fan_start_speed` and `fan_stop_speed`.  The names `min_fan_speed` and `min_fan_xxx_speed` are confusingly similar.

2020-04-11 21:00 UTC, x0rbl commented on README.md
> +        "min_fan_stop_speed": 25, // This is the minimum speed at which the fan begins spinning, between 0 & 255
The other settings describe how the service will control the fan.  These two settings, on the other hand, describe *physical properties* of the fan.  They aren't "configuration", so to speak, as they only have one correct value.  So I think they should be separated in some way.  Maybe you could split out `gpu_config` into two different JSON groupings like `fan_properties` vs. `fan_settings`.  (Or `gpu_properties` vs `gpu_settings` if you prefer?)

2020-04-11 21:00 UTC, x0rbl commented on README.md
> +        "average": 1, // How many last temp readings are used to average the temperature, unused for now.
(This comment is just a reminder to echo changes from the documentation in NvapiFansSvc.h up here again)

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            if ((current_speed == 0) and (new_speed < service_config.gpu_config.min_fan_start_speed)) {
Correct me if I'm wrong:

I think this should be:
```
if ((current_speed <= min_fan_stop_speed) && // If the fan is definitely not spinning
    (new_speed > min_fan_stop_speed) &&      // And if the fan *could* be spinning
    (new_speed < min_fan_start_speed)) {
```

Note that the inequalities will change if you want `min_fan_stop_speed` to mean "minimum speed at which it will keep spinning" vs "maximum speed at which it will stop".

But I'm also wondering if this is a good idea.  I'm imagining the fan switching on and off every few seconds (which is presumably what these fan properties aim to prevent).  Is that okay?

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        return ERROR; // Maybe find a better error but eh
Where is this defined?

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int average = 1;                 // How many last temp readings are used to average the temperature. Not implemented yet.
Recommending:
`How many of the recent temperature readings are averaged to calculate the "current" temperature, used in fan speed calculations. Not implemented`

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +
Just realized this is a duplicate function.  You could un-static the NvapiFansLib definition and add a declaration in NvapiFansLib.h, since you have a use for it elsewhere now

2020-04-11 21:00 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.cpp
> +			NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)(*NvAPI_QueryInterface)(0x60DED2ED);
I don't think you need the asterisk in `(*NvAPI_QueryInterface)(x)`, or any of the other calls to the function pointer.  You should just be able to do it like

`NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)NvAPI_QueryInterface(0x60DED2ED);`

2020-04-11 22:24 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
> +	utilization = api.getGPUUsage(gpu);
done

2020-04-11 22:28 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        service_config_t config_service{};
hehe yeah I got so confused a couple times, fixed

2020-04-11 22:30 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +    if ((draft_config.gpu_config.interval_s <= 1) || (draft_config.gpu_config.interval_s > 100) ) {
interval needs to be more or equal than 1 second between checks.
I also declare that 100 seconds between checks is too much =)

2020-04-11 22:39 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int interval_s = 2;     // Which interval in seconds between checks, between 1 & 100
Fine for 30 =)

2020-04-11 22:40 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int max_fan_speed = 200;         // Speed to set if temp is over max_temp_c. 255 is "max speed", between 0 & 255
ack

2020-04-11 22:55 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int min_fan_stop_speed = 25;     // This is the minimum speed at which the fan keeps spinning once started, between 0 & 255 aka minso
They do sometimes document these. I would just put there a "classic" value and let other people figure their shit out =)
I'd rather drop a word about that in the README.md, no one is going to read the code anyway

2020-04-11 23:00 UTC, conchyliculture commented on README.md
> +        "min_fan_stop_speed": 25, // This is the minimum speed at which the fan begins spinning, between 0 & 255
yeaaaahhh you could also argue the values might change as the fan ages.

I'll trust the users of my code will be as smart as the ones from [fancontrol](https://github.com/lm-sensors/lm-sensors/blob/master/prog/pwm/fancontrol) :)

2020-04-11 23:10 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +            if ((current_speed == 0) and (new_speed < service_config.gpu_config.min_fan_start_speed)) {
if current_speed is < min_fan_stop_speed, then we expect current_speed is 0

2020-04-11 23:15 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.h
> +    int average = 1;                 // How many last temp readings are used to average the temperature. Not implemented yet.
done

2020-04-11 23:31 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +
done

2020-04-11 23:36 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.cpp
> +			NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)(*NvAPI_QueryInterface)(0x60DED2ED);
done

2020-04-11 23:41 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        return ERROR; // Maybe find a better error but eh
used ERROR_BAD_UNIT

2020-04-12 01:21 UTC, x0rbl requested changes

2020-04-12 01:21 UTC, x0rbl commented on win/NvapiFansCli/NvapiFansCli.cpp
>  	res = api.getGPUFullname(gpu, gpu_name);
I can't comment on line 46, but I think you want `res &= api.getTemps(...)`

Also you can optionally say it like `bool res = api.getGPUFullname(gpu, gpu_name)` and remove the declaration a few lines up

2020-04-12 01:21 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        service_config_t service_config{};
You don't want to declare a new variable here.  You have a variable called `service_config` up above; that is the one that gets its config set via `loadConfig`.  If you create a new one here inside this while loop, then anything in this scope that refers to `service_config` will instead refer to this one.  And that is not what you want because this one was not initialized with `loadConfig`.

(I tried to update the previous conversation but it won't let me reply now that I clicked "Unresolve conversation")

2020-04-12 01:21 UTC, x0rbl commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +                && (new_speed > service_config.gpu_config.min_fan_stop_speed) // And if the fan *could* be spinning
If you're going with the "lowest speed at which the fan will continue spinning" definition then you should check `new_speed >= service_config.gpu_config.min_fan_stop_speed`

2020-04-12 01:21 UTC, x0rbl commented on win/NvapiFansLib/NvapiFansLib.cpp
> +			NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)(NvAPI_QueryInterface)(0x60DED2ED);
Just in case: You can remove the parentheses around the function pointer too, if you like.  I think that is a bit more readable

`NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)NvAPI_QueryInterface(0x60DED2ED);`

2020-04-12 09:47 UTC, conchyliculture commented on win/NvapiFansCli/NvapiFansCli.cpp
>  	res = api.getGPUFullname(gpu, gpu_name);
fixed

2020-04-12 09:49 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +        service_config_t service_config{};
done

2020-04-12 09:55 UTC, conchyliculture commented on win/NvapiFansSvc/NvapiFansSvc.cpp
> +                && (new_speed > service_config.gpu_config.min_fan_stop_speed) // And if the fan *could* be spinning
let's say > is safer :)
a difference of 1 here means 30 rpm (which is half the error range around the lowest speed that my 'expensive' fan can do)

2020-04-12 09:58 UTC, conchyliculture commented on win/NvapiFansLib/NvapiFansLib.cpp
> +			NvAPI_GPU_GetDynamicPstatesInfoEx = (NvAPI_GPU_GetDynamicPstatesInfoEx_t)(NvAPI_QueryInterface)(0x60DED2ED);
done

2020-04-12 10:18 UTC, x0rbl approved these changes

2020-04-12 10:58 UTC, merged